### ISSUE TITLE
Uitgebreidere README.md

### ISSUE THREAD

**Issue by lisannevvliet** [KaivWezel/Sprekende-kunst#1]
In de README.md staat momenteel enkel "Een applicatie die de kunst voor je zoekt en voordraagt.". Het zou fijner zijn als er uitgebreider beschreven staat om wat voor soort kunst het gaat (Rijksmuseum), waarop de gebruiker kan zoeken en wat het doel is hiervan. De API moet uiteindelijk ook beschreven worden in dit bestand, dat is ook nog niet gebeurd. Zie [https://github.com/cmda-minor-web/web-app-from-scratch-2122/blob/main/course/peer-review-1.md](https://github.com/cmda-minor-web/web-app-from-scratch-2122/blob/main/course/peer-review-1.md).

**Comment by KaivWezel** [comment]
Read me is bijna compleet
