### ISSUE TITLE
Boilerplate code in JavaScript

### ISSUE THREAD

**Issue by lisannevvliet** [KaivWezel/Sprekende-kunst#3]
Voor zowel nu als in de toekomst: probeer boilerplate code te herkennen en dit in een variabele of functie te zetten. Momenteel wordt `document.querySelector()` bijvoorbeeld drie keer gebruikt. Verder is de JavaScript compact, maar blijf hierop letten.

**Comment by KaivWezel** [comment]
Ja en nee, snippets werken ook
